import { motion } from 'motion/react';
import { Download, FileJson, FileText, Share2, Copy } from 'lucide-react';
import { Button } from './ui/button';
import { toast } from 'sonner';
import { format } from 'date-fns';

interface ExportDataProps {
  studyEntries: any[];
  goals: any[];
  streak: number;
  userLevel: number;
  userXP: number;
  appMode?: string;
}

export default function ExportData({ studyEntries, goals, streak, userLevel, userXP, appMode }: ExportDataProps) {
  const handleExportJSON = () => {
    const data = {
      mode: appMode,
      studyEntries,
      goals,
      streak,
      userLevel,
      userXP,
      exportedAt: new Date().toISOString(),
    };

    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    const modePrefix = appMode ? `${appMode}-` : '';
    a.download = `study-data-${modePrefix}${format(new Date(), 'yyyy-MM-dd')}.json`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success(`${appMode || 'Study'} data exported`);
  };

  const handleExportCSV = () => {
    const headers = ['Date', 'Subject', 'Chapter', 'Topic', 'Lecture Time (min)', 'Practice Time (min)', 'DPP', 'Score', 'Focus Score'];
    const rows = studyEntries.map((entry) => [
      format(new Date(entry.date), 'yyyy-MM-dd'),
      entry.subject,
      entry.chapter,
      entry.topic || '',
      entry.lectureTime,
      entry.practiceTime,
      entry.dppCompleted ? 'Yes' : 'No',
      entry.score || '',
      entry.focusScore || '',
    ]);

    const csv = [headers.join(','), ...rows.map((row) => row.join(','))].join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    const modePrefix = appMode ? `${appMode}-` : '';
    a.download = `study-data-${modePrefix}${format(new Date(), 'yyyy-MM-dd')}.csv`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success(`${appMode || 'Study'} data exported as CSV`);
  };

  const handleExportText = () => {
    const totalHours = studyEntries.reduce((sum, entry) => sum + (entry.lectureTime + entry.practiceTime) / 60, 0);
    const completedDPPs = studyEntries.filter((e) => e.dppCompleted).length;

    const text = `
STUDY TRACKER REPORT${appMode ? ` - ${appMode} MODE` : ''}
Generated: ${format(new Date(), 'PPP')}

═══════════════════════════════════════

📊 OVERVIEW
${appMode ? `Study Mode: ${appMode}\n` : ''}Level: ${userLevel}
XP: ${userXP}
Streak: ${streak} days
Total Sessions: ${studyEntries.length}
Total Hours: ${totalHours.toFixed(1)}
DPPs Completed: ${completedDPPs}

═══════════════════════════════════════

📚 STUDY SESSIONS

${studyEntries
  .map((entry, index) => {
    return `${index + 1}. ${format(new Date(entry.date), 'MMM d, yyyy')}
   Subject: ${entry.subject}
   Chapter: ${entry.chapter}
   ${entry.topic ? `Topic: ${entry.topic}\n   ` : ''}Time: ${((entry.lectureTime + entry.practiceTime) / 60).toFixed(1)}h
   ${entry.dppCompleted ? '✓ DPP Completed\n   ' : ''}${entry.score ? `Score: ${entry.score}%\n   ` : ''}${entry.focusScore ? `Focus: ${entry.focusScore}/100\n   ` : ''}`;
  })
  .join('\n\n')}

═══════════════════════════════════════

🎯 GOALS

${goals.length > 0 ? goals.map((goal, index) => `${index + 1}. ${goal.subject} - ${goal.type} (${goal.targetHours}h target)`).join('\n') : 'No goals set'}

═══════════════════════════════════════

Generated by Study Command Center
    `.trim();

    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    const modePrefix = appMode ? `${appMode}-` : '';
    a.download = `study-report-${modePrefix}${format(new Date(), 'yyyy-MM-dd')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success(`${appMode || 'Study'} report downloaded`);
  };

  const handleCopyStats = () => {
    const totalHours = studyEntries.reduce((sum, entry) => sum + (entry.lectureTime + entry.practiceTime) / 60, 0);
    const stats = `📊 My ${appMode || 'Study'} Stats:
Level ${userLevel} | ${streak} day streak 🔥
${studyEntries.length} sessions | ${totalHours.toFixed(1)} hours
Generated by Study Command Center`;

    navigator.clipboard.writeText(stats);
    toast.success('Stats copied to clipboard!');
  };

  const totalHours = studyEntries.reduce((sum, entry) => sum + (entry.lectureTime + entry.practiceTime) / 60, 0);
  const avgSessionLength = studyEntries.length > 0 ? totalHours / studyEntries.length : 0;

  return (
    <div className="min-h-full p-6 pb-20">
      <motion.div className="max-w-4xl mx-auto" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
        <div className="mb-6">
          <div className="flex items-center gap-3 mb-2">
            <h1 className="text-3xl tracking-tight">Export Data</h1>
            {appMode && (
              <div className="px-3 py-1 rounded-full bg-primary/20 border border-primary/30">
                <span className="text-xs font-medium text-primary">{appMode} Mode</span>
              </div>
            )}
          </div>
          <p className="text-muted-foreground text-sm">Download your {appMode || 'study'} data in various formats</p>
        </div>

        {/* Summary Stats */}
        <motion.div
          className="bg-gradient-to-br from-primary/10 to-accent/10 border border-primary/20 rounded-xl p-6 mb-8"
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
        >
          <h3 className="text-lg mb-4">Quick Summary</h3>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
            <div className="bg-background/50 rounded-lg p-3">
              <div className="text-2xl font-bold font-mono text-primary">{studyEntries.length}</div>
              <div className="text-xs text-muted-foreground">Sessions</div>
            </div>
            <div className="bg-background/50 rounded-lg p-3">
              <div className="text-2xl font-bold font-mono text-accent">{totalHours.toFixed(1)}</div>
              <div className="text-xs text-muted-foreground">Total Hours</div>
            </div>
            <div className="bg-background/50 rounded-lg p-3">
              <div className="text-2xl font-bold font-mono text-green-400">{streak}</div>
              <div className="text-xs text-muted-foreground">Day Streak</div>
            </div>
            <div className="bg-background/50 rounded-lg p-3">
              <div className="text-2xl font-bold font-mono text-yellow-400">{userLevel}</div>
              <div className="text-xs text-muted-foreground">Level</div>
            </div>
          </div>
        </motion.div>

        {/* Export Options */}
        <div className="space-y-4">
          <motion.div
            className="bg-card border border-border rounded-xl p-6"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
          >
            <div className="flex items-start gap-4">
              <div className="w-12 h-12 rounded-lg bg-primary/10 flex items-center justify-center flex-shrink-0">
                <FileJson className="w-6 h-6 text-primary" />
              </div>
              <div className="flex-1">
                <h3 className="text-lg mb-2">Export as JSON</h3>
                <p className="text-sm text-muted-foreground mb-4">
                  Complete data export in JSON format. Best for backups and importing to other apps.
                </p>
                <Button onClick={handleExportJSON} className="bg-primary hover:bg-primary/90 text-black">
                  <Download className="w-4 h-4 mr-2" />
                  Download JSON
                </Button>
              </div>
            </div>
          </motion.div>

          <motion.div
            className="bg-card border border-border rounded-xl p-6"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
          >
            <div className="flex items-start gap-4">
              <div className="w-12 h-12 rounded-lg bg-accent/10 flex items-center justify-center flex-shrink-0">
                <FileText className="w-6 h-6 text-accent" />
              </div>
              <div className="flex-1">
                <h3 className="text-lg mb-2">Export as CSV</h3>
                <p className="text-sm text-muted-foreground mb-4">
                  Spreadsheet-compatible format. Perfect for Excel, Google Sheets, and data analysis.
                </p>
                <Button onClick={handleExportCSV} className="bg-accent hover:bg-accent/90 text-black">
                  <Download className="w-4 h-4 mr-2" />
                  Download CSV
                </Button>
              </div>
            </div>
          </motion.div>

          <motion.div
            className="bg-card border border-border rounded-xl p-6"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3 }}
          >
            <div className="flex items-start gap-4">
              <div className="w-12 h-12 rounded-lg bg-green-400/10 flex items-center justify-center flex-shrink-0">
                <FileText className="w-6 h-6 text-green-400" />
              </div>
              <div className="flex-1">
                <h3 className="text-lg mb-2">Export as Text Report</h3>
                <p className="text-sm text-muted-foreground mb-4">
                  Human-readable report with all your study data. Great for printing or sharing.
                </p>
                <Button onClick={handleExportText} className="bg-green-400 hover:bg-green-500 text-black">
                  <Download className="w-4 h-4 mr-2" />
                  Download Report
                </Button>
              </div>
            </div>
          </motion.div>

          <motion.div
            className="bg-card border border-border rounded-xl p-6"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.4 }}
          >
            <div className="flex items-start gap-4">
              <div className="w-12 h-12 rounded-lg bg-yellow-400/10 flex items-center justify-center flex-shrink-0">
                <Share2 className="w-6 h-6 text-yellow-400" />
              </div>
              <div className="flex-1">
                <h3 className="text-lg mb-2">Share Stats</h3>
                <p className="text-sm text-muted-foreground mb-4">
                  Copy your stats summary to clipboard for sharing on social media or with friends.
                </p>
                <Button onClick={handleCopyStats} className="bg-yellow-400 hover:bg-yellow-500 text-black">
                  <Copy className="w-4 h-4 mr-2" />
                  Copy Stats
                </Button>
              </div>
            </div>
          </motion.div>
        </div>

        {studyEntries.length === 0 && (
          <div className="mt-8 bg-card border border-border rounded-xl p-12 text-center">
            <div className="text-6xl mb-4">📦</div>
            <h3 className="text-xl mb-2">No Data to Export</h3>
            <p className="text-muted-foreground mb-2">No {appMode || 'study'} sessions recorded yet</p>
            {appMode && (
              <p className="text-xs text-muted-foreground">
                Each mode has separate data. Switch modes in Settings to view other data.
              </p>
            )}
          </div>
        )}

        {studyEntries.length > 0 && appMode && (
          <div className="mt-6 p-4 rounded-lg bg-primary/10 border border-primary/30 text-center">
            <p className="text-xs text-primary">
              💡 Exporting {appMode} mode data only. Other modes have separate data.
            </p>
          </div>
        )}
      </motion.div>
    </div>
  );
}
